version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - kramdown_rpf-bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: kramdown_rpf-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Run rspec
      - run:
          name: Run rspec
          command: |
            bundle exec rspec
