version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Run rspec
      - run:
          name: Run rspec
          command: |
            bundle exec rspec
